// <auto-generated />
using System;
using HeerlijkeHerinneringen.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeerlijkeHerinneringen.Migrations
{
    [DbContext(typeof(HeerlijkeHerinneringenContext))]
    [Migration("20240727102542_ChefNaam")]
    partial class ChefNaam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Afbeelding", b =>
                {
                    b.Property<int>("AfbeeldingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AfbeeldingId"));

                    b.Property<string>("AfbeeldingNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AfbeeldingUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.HasKey("AfbeeldingId");

                    b.HasIndex("ReceptId");

                    b.ToTable("Afbeeldings");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Benodigdheid", b =>
                {
                    b.Property<int>("BenodigdheidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenodigdheidId"));

                    b.Property<string>("BenodigdheidNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BenodigdheidId");

                    b.ToTable("Benodigdheids");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Chef", b =>
                {
                    b.Property<int>("ChefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChefId"));

                    b.Property<string>("ChefFamilieNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChefVoorNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChefId");

                    b.ToTable("Chefs");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.MenuGang", b =>
                {
                    b.Property<int>("MenuGangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuGangId"));

                    b.Property<string>("MenuGangName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuGangId");

                    b.ToTable("MenuGangs");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Recept", b =>
                {
                    b.Property<int>("ReceptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceptId"));

                    b.Property<DateTime?>("AanmaakDatum")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Afbeelding")
                        .HasColumnType("tinyint");

                    b.Property<int>("ChefId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuGangId")
                        .HasColumnType("int");

                    b.Property<int>("TemperatuurId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeGerechtId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("ReceptId");

                    b.HasIndex("ChefId");

                    b.HasIndex("MenuGangId");

                    b.HasIndex("TemperatuurId");

                    b.HasIndex("TypeGerechtId");

                    b.ToTable("Recepts");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.ReceptBenodigdheid", b =>
                {
                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.Property<int>("BenodigdheidId")
                        .HasColumnType("int");

                    b.Property<string>("Hoeveelheid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptBenodigdheidId")
                        .HasColumnType("int");

                    b.HasKey("ReceptId", "BenodigdheidId");

                    b.HasIndex("BenodigdheidId");

                    b.ToTable("ReceptBenodigdheids");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.ReceptIngredient", b =>
                {
                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("Eenheid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoeveelheid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptIngredientId")
                        .HasColumnType("int");

                    b.HasKey("ReceptId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ReceptIngredients");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.ReceptStap", b =>
                {
                    b.Property<int>("ReceptStapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceptStapId"));

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.Property<int>("Volgorde")
                        .HasColumnType("int");

                    b.HasKey("ReceptStapId");

                    b.HasIndex("ReceptId");

                    b.ToTable("ReceptStaps");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Temperatuur", b =>
                {
                    b.Property<int>("TemperatuurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemperatuurId"));

                    b.Property<string>("TemperatuurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemperatuurId");

                    b.ToTable("Temperatuurs");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.TypeGerecht", b =>
                {
                    b.Property<int>("TypeGerechtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeGerechtId"));

                    b.Property<string>("TypeGerechtName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeGerechtId");

                    b.ToTable("TypeGerechts");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Afbeelding", b =>
                {
                    b.HasOne("HeerlijkeHerinneringen.Data.Models.Recept", "Recept")
                        .WithMany()
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Recept", b =>
                {
                    b.HasOne("HeerlijkeHerinneringen.Data.Models.Chef", "Chef")
                        .WithMany("Recepts")
                        .HasForeignKey("ChefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeerlijkeHerinneringen.Data.Models.MenuGang", "MenuGang")
                        .WithMany("Recepts")
                        .HasForeignKey("MenuGangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeerlijkeHerinneringen.Data.Models.Temperatuur", "Temperatuur")
                        .WithMany("Recepts")
                        .HasForeignKey("TemperatuurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeerlijkeHerinneringen.Data.Models.TypeGerecht", "TypeGerecht")
                        .WithMany("Recepts")
                        .HasForeignKey("TypeGerechtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chef");

                    b.Navigation("MenuGang");

                    b.Navigation("Temperatuur");

                    b.Navigation("TypeGerecht");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.ReceptBenodigdheid", b =>
                {
                    b.HasOne("HeerlijkeHerinneringen.Data.Models.Benodigdheid", "Benodigdheid")
                        .WithMany("ReceptBenodigdheids")
                        .HasForeignKey("BenodigdheidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeerlijkeHerinneringen.Data.Models.Recept", "Recept")
                        .WithMany("ReceptBenodigdheids")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benodigdheid");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.ReceptIngredient", b =>
                {
                    b.HasOne("HeerlijkeHerinneringen.Data.Models.Ingredient", "Ingredient")
                        .WithMany("ReceptIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeerlijkeHerinneringen.Data.Models.Recept", "Recept")
                        .WithMany("ReceptIngredients")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.ReceptStap", b =>
                {
                    b.HasOne("HeerlijkeHerinneringen.Data.Models.Recept", "Recept")
                        .WithMany("ReceptStaps")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Benodigdheid", b =>
                {
                    b.Navigation("ReceptBenodigdheids");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Chef", b =>
                {
                    b.Navigation("Recepts");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Ingredient", b =>
                {
                    b.Navigation("ReceptIngredients");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.MenuGang", b =>
                {
                    b.Navigation("Recepts");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Recept", b =>
                {
                    b.Navigation("ReceptBenodigdheids");

                    b.Navigation("ReceptIngredients");

                    b.Navigation("ReceptStaps");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.Temperatuur", b =>
                {
                    b.Navigation("Recepts");
                });

            modelBuilder.Entity("HeerlijkeHerinneringen.Data.Models.TypeGerecht", b =>
                {
                    b.Navigation("Recepts");
                });
#pragma warning restore 612, 618
        }
    }
}
